// GameplayEngine.sol – complete ABI (Base Sepolia verified)
// Event names must match contract exactly (camelCase).
export const GameplayEngineAbi = [
  {
    inputs: [
      { internalType: "address", name: "_gameContract", type: "address" },
      { internalType: "string", name: "_source", type: "string" },
      { internalType: "uint64", name: "_subscriptionId", type: "uint64" },
      { internalType: "address", name: "_router", type: "address" },
      { internalType: "bytes32", name: "_donId", type: "bytes32" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "EmptyArgs", type: "error" },
  { inputs: [], name: "EmptySecrets", type: "error" },
  { inputs: [], name: "EmptySource", type: "error" },
  { inputs: [], name: "GameEng__AlreadyRegistered", type: "error" },
  { inputs: [], name: "GameEng__CannotBeZeroAddress", type: "error" },
  { inputs: [], name: "GameEng__Full", type: "error" },
  { inputs: [], name: "GameEng__NotAllowListed", type: "error" },
  { inputs: [], name: "GameEng__NotOpen", type: "error" },
  { inputs: [], name: "GameEng__ProphetNumberError", type: "error" },
  { inputs: [], name: "Game__MinimumTimeNotPassed", type: "error" },
  { inputs: [], name: "Game__NotAllowed", type: "error" },
  { inputs: [], name: "Game__NotInProgress", type: "error" },
  { inputs: [], name: "Game__OutOfTurn", type: "error" },
  { inputs: [], name: "Game__ProphetNotFree", type: "error" },
  { inputs: [], name: "NoInlineSecrets", type: "error" },
  { inputs: [], name: "OnlyRouterCanFulfill", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    name: "UnexpectedRequestID",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
    ],
    name: "OwnershipTransferRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "id", type: "bytes32" },
    ],
    name: "RequestFulfilled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "id", type: "bytes32" },
    ],
    name: "RequestSent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "character",
        type: "string",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "response",
        type: "bytes",
      },
      { indexed: false, internalType: "bytes", name: "err", type: "bytes" },
    ],
    name: "Response",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bool", name: "isSuccess", type: "bool" },
      {
        indexed: false,
        internalType: "bool",
        name: "targetIsAlive",
        type: "bool",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "currentProphetTurn",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_target",
        type: "uint256",
      },
    ],
    name: "accusation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bool",
        name: "allowListEnabled",
        type: "bool",
      },
    ],
    name: "allowListEnabledSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "action",
        type: "uint256",
      },
    ],
    name: "chainlinkRequestSent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "forceMiracleTriggered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
    ],
    name: "gameStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bool", name: "isSuccess", type: "bool" },
      {
        indexed: true,
        internalType: "uint256",
        name: "currentProphetTurn",
        type: "uint256",
      },
    ],
    name: "miracleAttempted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "prophetNumber",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
    ],
    name: "prophetEnteredGame",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "target",
        type: "uint256",
      },
      { indexed: true, internalType: "bool", name: "isSuccess", type: "bool" },
      {
        indexed: true,
        internalType: "uint256",
        name: "currentProphetTurn",
        type: "uint256",
      },
    ],
    name: "smiteAttempted",
    type: "event",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_target", type: "uint256" }],
    name: "accuseOfBlasphemy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_target", type: "uint256" }],
    name: "attemptSmite",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint8", name: "_donHostedSecretsSlotID", type: "uint8" },
    ],
    name: "changeDonHostedSecretsSlotID",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "_donHostedSecretsVersion",
        type: "uint64",
      },
    ],
    name: "changeDonHostedSecretsVersion",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "_subscriptionId", type: "uint64" },
    ],
    name: "changeFunctionsSubscriptionId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "_gasLimit", type: "uint32" }],
    name: "changeGasLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "_allowListProof", type: "bytes32[]" },
    ],
    name: "enterGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "forceMiracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getOwner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "requestId", type: "bytes32" },
      { internalType: "bytes", name: "response", type: "bytes" },
      { internalType: "bytes", name: "err", type: "bytes" },
    ],
    name: "handleOracleFulfillment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "performMiracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "s_allowListEnabled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_allowListRoot",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_lastFunctionError",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_lastFunctionRequestId",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_lastFunctionResponse",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "_allowListEnabled", type: "bool" }],
    name: "setAllowListEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_allowListRoot", type: "bytes32" },
    ],
    name: "setAllowListRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_source", type: "string" }],
    name: "setSource",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "to", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
