// Phenomenon.sol – complete ABI (Base Sepolia verified)
// Event names must match contract exactly (camelCase).
export const PhenomenonAbi = [
  {
    inputs: [
      { internalType: "uint256", name: "_maxInterval", type: "uint256" },
      { internalType: "uint256", name: "_minInterval", type: "uint256" },
      { internalType: "uint256", name: "_entranceFee", type: "uint256" },
      { internalType: "uint256", name: "_protocolFee", type: "uint256" },
      { internalType: "uint16", name: "_numProphets", type: "uint16" },
      { internalType: "address", name: "_gameToken", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "Game__CannotBeZeroAddress", type: "error" },
  { inputs: [], name: "Game__NotAllowed", type: "error" },
  { inputs: [], name: "Game__NotEnoughTicketsOwned", type: "error" },
  { inputs: [], name: "Game__NotInProgress", type: "error" },
  { inputs: [], name: "Game__OnlyController", type: "error" },
  { inputs: [], name: "Game__OnlyOwner", type: "error" },
  { inputs: [], name: "Game__ProphetNumberError", type: "error" },
  { inputs: [], name: "Game__ProtocolFeeTooHigh", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "nextProphetTurn",
        type: "uint256",
      },
    ],
    name: "currentTurn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "entranceFee",
        type: "uint256",
      },
    ],
    name: "entranceFeeSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokensPerTicket",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "currentProphetTurn",
        type: "uint256",
      },
    ],
    name: "gameEnded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
    ],
    name: "gameNumberSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "newGameNumber",
        type: "uint256",
      },
    ],
    name: "gameReset",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "enum Phenomenon.GameState",
        name: "gameStatus",
        type: "uint8",
      },
    ],
    name: "gameStatusSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "gameplayEngine",
        type: "address",
      },
    ],
    name: "gameplayEngineSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "maxInterval",
        type: "uint256",
      },
    ],
    name: "maxIntervalSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "minInterval",
        type: "uint256",
      },
    ],
    name: "minIntervalSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint16",
        name: "numberOfProphets",
        type: "uint16",
      },
    ],
    name: "numberOfProphetsSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bool",
        name: "ownerCanTransferAnyToken",
        type: "bool",
      },
    ],
    name: "ownerCanTransferAnyTokenSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "ownerTokenBalance",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "ownerTokenBalanceSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "prophet",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "prophetNum",
        type: "uint256",
      },
    ],
    name: "prophetRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "prophet",
        type: "address",
      },
      { indexed: true, internalType: "bool", name: "isAlive", type: "bool" },
      { indexed: false, internalType: "bool", name: "isFree", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "args",
        type: "uint256",
      },
    ],
    name: "prophetUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "randomnessSeed",
        type: "uint256",
      },
    ],
    name: "randomnessSeedSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "ticketEngine",
        type: "address",
      },
    ],
    name: "ticketEngineSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokensDepositedThisGame",
        type: "uint256",
      },
    ],
    name: "tokensDepositedThisGameSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokensPerTicket",
        type: "uint256",
      },
    ],
    name: "tokensPerTicketSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameNumber",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "totalTickets",
        type: "uint256",
      },
    ],
    name: "totalTicketsSet",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "acolytes",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "allegiance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "applyProtocolFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "burnOwnerGodMode",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_gameNumber", type: "uint256" },
      { internalType: "address", name: "target", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "burnWinningTicketsByGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newFee", type: "uint256" }],
    name: "changeEntryFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_status", type: "uint256" }],
    name: "changeGameStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "newGameplayEngine", type: "address" },
    ],
    name: "changeGameplayEngine",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "changeOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "newTicketEngine", type: "address" },
    ],
    name: "changeTicketEngine",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "checkProphetList",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "currentProphetTurn",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "target", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "decreaseAcolytes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "target", type: "uint256" }],
    name: "decreaseHighPriest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "target", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "decreaseTicketsToValhalla",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "decreaseTokensDepositedThisGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "decreaseTotalTickets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "depositGameTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gameStatus",
    outputs: [
      { internalType: "enum Phenomenon.GameState", name: "", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentProphetTurn",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGameToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOwner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOwnerTokenBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_prophetNum", type: "uint256" }],
    name: "getProphetData",
    outputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRandomnessSeed",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_playerNum", type: "uint256" }],
    name: "getTicketShare",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "highPriestsByProphet",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "target", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "increaseAcolytes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "target", type: "uint256" }],
    name: "increaseHighPriest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "target", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "increaseTicketsToValhalla",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "increaseTokenDepositedThisGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "increaseTotalTickets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum Phenomenon.GameState",
        name: "_status",
        type: "uint8",
      },
    ],
    name: "ownerChangeGameState",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "address", name: "_destination", type: "address" },
    ],
    name: "ownerTokenTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "prophetList",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "prophets",
    outputs: [
      { internalType: "address", name: "playerAddress", type: "address" },
      { internalType: "bool", name: "isAlive", type: "bool" },
      { internalType: "bool", name: "isFree", type: "bool" },
      { internalType: "uint256", name: "args", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_prophet", type: "address" }],
    name: "registerProphet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "_numberOfPlayers", type: "uint16" },
    ],
    name: "reset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "returnGameTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "s_entranceFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_gameNumber",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_lastRoundTimestamp",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_maxInterval",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_minInterval",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_numberOfProphets",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_prophetsRemaining",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_protocolFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_tokensDepositedThisGame",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_totalTickets",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newMaxInterval", type: "uint256" },
    ],
    name: "setMaxInterval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newMinInterval", type: "uint256" },
    ],
    name: "setMinInterval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "player", type: "address" },
      { internalType: "uint256", name: "target", type: "uint256" },
    ],
    name: "setPlayerAllegiance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_prophetNum", type: "uint256" }],
    name: "setProphetTurn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_protocolFee", type: "uint256" },
    ],
    name: "setProtocolFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "randomnessSeed", type: "uint256" },
    ],
    name: "setRandomnessSeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "ticketsToValhalla",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "tokensPerTicket",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_destination", type: "address" },
    ],
    name: "transferOwnerTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "turnManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_prophetNum", type: "uint256" },
      { internalType: "uint256", name: "_args", type: "uint256" },
    ],
    name: "updateProphetArgs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_prophetNum", type: "uint256" },
      { internalType: "bool", name: "_isFree", type: "bool" },
    ],
    name: "updateProphetFreedom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_prophetNum", type: "uint256" },
      { internalType: "bool", name: "_isAlive", type: "bool" },
    ],
    name: "updateProphetLife",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_add", type: "uint256" },
      { internalType: "uint256", name: "_subtract", type: "uint256" },
    ],
    name: "updateProphetsRemaining",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
